name: Setup Node

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: '20'
      - run: node --version
      - run: npm --version

# act workflow_dispatch -W .github/workflows/setup-node.yml
# VM starts → checkout code → install Node.js → run steps → VM destroyed
